---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demos-app
    spec:
      containers:
      - name: demo-app
        image: "mrajucha922/java-demo-app:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
spec:
  selector:
    app: demo-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80